export interface SeededFood {
  name: string;
  brand: string | null;
  category: string;
  serving_size_g: number;
  calories_kcal: number;
  protein_g: number;
  fat_g: number;
  carbs_g: number;
}

// Nutritional values per 100g. Sources: ICMR Nutritive Value of Indian Foods,
// NIN (National Institute of Nutrition) tables, and manufacturer data for packaged items.
export const INDIAN_FOODS_SEED: SeededFood[] = [
  // ── Dal / Lentils ────────────────────────────────────────────────────────────
  {
    name: "Masoor Dal (Red Lentils, cooked)",
    brand: null,
    category: "Dal",
    serving_size_g: 150,
    calories_kcal: 116,
    protein_g: 9.0,
    fat_g: 0.4,
    carbs_g: 20.1,
  },
  {
    name: "Moong Dal (Yellow, cooked)",
    brand: null,
    category: "Dal",
    serving_size_g: 150,
    calories_kcal: 104,
    protein_g: 7.6,
    fat_g: 0.4,
    carbs_g: 18.3,
  },
  {
    name: "Chana Dal (Split Bengal Gram, cooked)",
    brand: null,
    category: "Dal",
    serving_size_g: 150,
    calories_kcal: 164,
    protein_g: 8.9,
    fat_g: 2.7,
    carbs_g: 27.0,
  },
  {
    name: "Toor Dal (Arhar Dal, cooked)",
    brand: null,
    category: "Dal",
    serving_size_g: 150,
    calories_kcal: 118,
    protein_g: 7.2,
    fat_g: 0.4,
    carbs_g: 20.6,
  },
  {
    name: "Rajma (Kidney Beans, cooked)",
    brand: null,
    category: "Dal",
    serving_size_g: 150,
    calories_kcal: 127,
    protein_g: 8.7,
    fat_g: 0.5,
    carbs_g: 22.8,
  },
  {
    name: "Urad Dal (Black Gram, cooked)",
    brand: null,
    category: "Dal",
    serving_size_g: 150,
    calories_kcal: 105,
    protein_g: 7.0,
    fat_g: 0.4,
    carbs_g: 18.4,
  },
  {
    name: "Moong Dal (Whole Green, cooked)",
    brand: null,
    category: "Dal",
    serving_size_g: 150,
    calories_kcal: 105,
    protein_g: 7.0,
    fat_g: 0.4,
    carbs_g: 19.2,
  },
  {
    name: "Kabuli Chana (Chickpeas, cooked)",
    brand: null,
    category: "Dal",
    serving_size_g: 150,
    calories_kcal: 164,
    protein_g: 8.9,
    fat_g: 2.6,
    carbs_g: 27.4,
  },

  // ── Rice Dishes ──────────────────────────────────────────────────────────────
  {
    name: "Plain Steamed Rice (cooked)",
    brand: null,
    category: "Rice",
    serving_size_g: 200,
    calories_kcal: 130,
    protein_g: 2.7,
    fat_g: 0.3,
    carbs_g: 28.2,
  },
  {
    name: "Jeera Rice",
    brand: null,
    category: "Rice",
    serving_size_g: 200,
    calories_kcal: 148,
    protein_g: 2.8,
    fat_g: 2.2,
    carbs_g: 29.0,
  },
  {
    name: "Veg Pulao",
    brand: null,
    category: "Rice",
    serving_size_g: 200,
    calories_kcal: 155,
    protein_g: 3.2,
    fat_g: 3.5,
    carbs_g: 28.0,
  },
  {
    name: "Khichdi (Moong Dal)",
    brand: null,
    category: "Rice",
    serving_size_g: 250,
    calories_kcal: 110,
    protein_g: 4.5,
    fat_g: 2.0,
    carbs_g: 19.5,
  },
  {
    name: "Chicken Biryani",
    brand: null,
    category: "Rice",
    serving_size_g: 300,
    calories_kcal: 185,
    protein_g: 9.5,
    fat_g: 6.5,
    carbs_g: 24.0,
  },
  {
    name: "Veg Biryani",
    brand: null,
    category: "Rice",
    serving_size_g: 250,
    calories_kcal: 160,
    protein_g: 3.8,
    fat_g: 5.0,
    carbs_g: 25.5,
  },
  {
    name: "Curd Rice",
    brand: null,
    category: "Rice",
    serving_size_g: 200,
    calories_kcal: 120,
    protein_g: 3.5,
    fat_g: 2.2,
    carbs_g: 22.0,
  },
  {
    name: "Lemon Rice",
    brand: null,
    category: "Rice",
    serving_size_g: 200,
    calories_kcal: 145,
    protein_g: 2.5,
    fat_g: 3.5,
    carbs_g: 27.0,
  },

  // ── Breads ───────────────────────────────────────────────────────────────────
  {
    name: "Roti / Chapati (plain wheat)",
    brand: null,
    category: "Bread",
    serving_size_g: 40,
    calories_kcal: 297,
    protein_g: 9.7,
    fat_g: 3.7,
    carbs_g: 55.0,
  },
  {
    name: "Naan (plain)",
    brand: null,
    category: "Bread",
    serving_size_g: 90,
    calories_kcal: 317,
    protein_g: 9.0,
    fat_g: 7.8,
    carbs_g: 52.0,
  },
  {
    name: "Butter Naan",
    brand: null,
    category: "Bread",
    serving_size_g: 90,
    calories_kcal: 357,
    protein_g: 9.0,
    fat_g: 12.0,
    carbs_g: 52.0,
  },
  {
    name: "Paratha (plain)",
    brand: null,
    category: "Bread",
    serving_size_g: 80,
    calories_kcal: 324,
    protein_g: 8.2,
    fat_g: 10.5,
    carbs_g: 50.5,
  },
  {
    name: "Aloo Paratha",
    brand: null,
    category: "Bread",
    serving_size_g: 120,
    calories_kcal: 260,
    protein_g: 6.5,
    fat_g: 8.5,
    carbs_g: 42.0,
  },
  {
    name: "Puri (fried wheat bread)",
    brand: null,
    category: "Bread",
    serving_size_g: 30,
    calories_kcal: 408,
    protein_g: 8.5,
    fat_g: 18.0,
    carbs_g: 55.0,
  },
  {
    name: "Bhatura (fried fermented bread)",
    brand: null,
    category: "Bread",
    serving_size_g: 80,
    calories_kcal: 370,
    protein_g: 8.0,
    fat_g: 16.0,
    carbs_g: 50.0,
  },
  {
    name: "Missi Roti (besan + atta)",
    brand: null,
    category: "Bread",
    serving_size_g: 50,
    calories_kcal: 310,
    protein_g: 11.5,
    fat_g: 5.5,
    carbs_g: 55.0,
  },
  {
    name: "Tandoori Roti",
    brand: null,
    category: "Bread",
    serving_size_g: 60,
    calories_kcal: 300,
    protein_g: 9.5,
    fat_g: 4.0,
    carbs_g: 56.0,
  },

  // ── Curries ──────────────────────────────────────────────────────────────────
  {
    name: "Dal Makhani",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 135,
    protein_g: 6.5,
    fat_g: 5.5,
    carbs_g: 17.5,
  },
  {
    name: "Butter Chicken (Murgh Makhani)",
    brand: null,
    category: "Curry",
    serving_size_g: 250,
    calories_kcal: 150,
    protein_g: 12.0,
    fat_g: 7.5,
    carbs_g: 9.0,
  },
  {
    name: "Palak Paneer",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 145,
    protein_g: 8.0,
    fat_g: 9.5,
    carbs_g: 7.5,
  },
  {
    name: "Paneer Butter Masala",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 195,
    protein_g: 8.5,
    fat_g: 13.5,
    carbs_g: 11.0,
  },
  {
    name: "Chole (Chana Masala)",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 140,
    protein_g: 7.0,
    fat_g: 4.5,
    carbs_g: 20.0,
  },
  {
    name: "Aloo Gobi",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 95,
    protein_g: 2.8,
    fat_g: 4.5,
    carbs_g: 13.0,
  },
  {
    name: "Matar Paneer",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 180,
    protein_g: 9.0,
    fat_g: 11.0,
    carbs_g: 12.0,
  },
  {
    name: "Chicken Curry",
    brand: null,
    category: "Curry",
    serving_size_g: 250,
    calories_kcal: 155,
    protein_g: 14.0,
    fat_g: 8.5,
    carbs_g: 6.5,
  },
  {
    name: "Mutton Curry",
    brand: null,
    category: "Curry",
    serving_size_g: 250,
    calories_kcal: 185,
    protein_g: 15.5,
    fat_g: 11.0,
    carbs_g: 6.5,
  },
  {
    name: "Fish Curry",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 120,
    protein_g: 14.5,
    fat_g: 5.5,
    carbs_g: 5.0,
  },
  {
    name: "Egg Curry",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 140,
    protein_g: 9.5,
    fat_g: 8.5,
    carbs_g: 7.0,
  },
  {
    name: "Pav Bhaji",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 120,
    protein_g: 3.5,
    fat_g: 5.5,
    carbs_g: 17.0,
  },
  {
    name: "Baingan Bharta (Smoked Eggplant)",
    brand: null,
    category: "Curry",
    serving_size_g: 150,
    calories_kcal: 72,
    protein_g: 2.0,
    fat_g: 4.5,
    carbs_g: 7.5,
  },
  {
    name: "Shahi Paneer",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 210,
    protein_g: 9.5,
    fat_g: 15.5,
    carbs_g: 10.5,
  },
  {
    name: "Chicken Korma",
    brand: null,
    category: "Curry",
    serving_size_g: 250,
    calories_kcal: 175,
    protein_g: 13.5,
    fat_g: 10.5,
    carbs_g: 7.5,
  },
  {
    name: "Kadhi (Yogurt Curry)",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 80,
    protein_g: 3.5,
    fat_g: 4.0,
    carbs_g: 9.0,
  },
  {
    name: "Kadhi Pakora",
    brand: null,
    category: "Curry",
    serving_size_g: 200,
    calories_kcal: 105,
    protein_g: 4.5,
    fat_g: 5.5,
    carbs_g: 11.5,
  },
  {
    name: "Rajma Chawal (Rajma with Rice)",
    brand: null,
    category: "Curry",
    serving_size_g: 350,
    calories_kcal: 128,
    protein_g: 5.5,
    fat_g: 2.0,
    carbs_g: 24.5,
  },

  // ── Breakfast ────────────────────────────────────────────────────────────────
  {
    name: "Idli (steamed rice cake)",
    brand: null,
    category: "Breakfast",
    serving_size_g: 120,
    calories_kcal: 154,
    protein_g: 3.5,
    fat_g: 0.4,
    carbs_g: 32.8,
  },
  {
    name: "Plain Dosa",
    brand: null,
    category: "Breakfast",
    serving_size_g: 80,
    calories_kcal: 168,
    protein_g: 3.9,
    fat_g: 3.7,
    carbs_g: 30.0,
  },
  {
    name: "Masala Dosa",
    brand: null,
    category: "Breakfast",
    serving_size_g: 200,
    calories_kcal: 175,
    protein_g: 4.5,
    fat_g: 5.5,
    carbs_g: 29.0,
  },
  {
    name: "Upma (Semolina)",
    brand: null,
    category: "Breakfast",
    serving_size_g: 200,
    calories_kcal: 145,
    protein_g: 4.0,
    fat_g: 4.5,
    carbs_g: 23.5,
  },
  {
    name: "Poha (Flattened Rice, cooked)",
    brand: null,
    category: "Breakfast",
    serving_size_g: 200,
    calories_kcal: 130,
    protein_g: 2.5,
    fat_g: 3.5,
    carbs_g: 23.0,
  },
  {
    name: "Medu Vada",
    brand: null,
    category: "Breakfast",
    serving_size_g: 60,
    calories_kcal: 290,
    protein_g: 8.5,
    fat_g: 15.0,
    carbs_g: 32.0,
  },
  {
    name: "Uttapam",
    brand: null,
    category: "Breakfast",
    serving_size_g: 120,
    calories_kcal: 160,
    protein_g: 4.5,
    fat_g: 4.5,
    carbs_g: 27.0,
  },
  {
    name: "Ven Pongal",
    brand: null,
    category: "Breakfast",
    serving_size_g: 200,
    calories_kcal: 155,
    protein_g: 5.0,
    fat_g: 5.5,
    carbs_g: 24.0,
  },
  {
    name: "Pesarattu (Moong Dal Dosa)",
    brand: null,
    category: "Breakfast",
    serving_size_g: 100,
    calories_kcal: 172,
    protein_g: 8.5,
    fat_g: 4.0,
    carbs_g: 27.0,
  },
  {
    name: "Misal Pav",
    brand: null,
    category: "Breakfast",
    serving_size_g: 250,
    calories_kcal: 185,
    protein_g: 7.5,
    fat_g: 6.5,
    carbs_g: 27.0,
  },
  {
    name: "Chole Bhature",
    brand: null,
    category: "Breakfast",
    serving_size_g: 300,
    calories_kcal: 240,
    protein_g: 8.0,
    fat_g: 10.5,
    carbs_g: 33.0,
  },
  {
    name: "Sabudana Khichdi",
    brand: null,
    category: "Breakfast",
    serving_size_g: 200,
    calories_kcal: 205,
    protein_g: 3.0,
    fat_g: 6.5,
    carbs_g: 37.0,
  },

  // ── Snacks ───────────────────────────────────────────────────────────────────
  {
    name: "Samosa (potato filled, fried)",
    brand: null,
    category: "Snack",
    serving_size_g: 85,
    calories_kcal: 308,
    protein_g: 4.5,
    fat_g: 17.0,
    carbs_g: 36.0,
  },
  {
    name: "Onion Pakora (Bhajia)",
    brand: null,
    category: "Snack",
    serving_size_g: 100,
    calories_kcal: 275,
    protein_g: 6.0,
    fat_g: 14.5,
    carbs_g: 33.0,
  },
  {
    name: "Vada Pav",
    brand: null,
    category: "Snack",
    serving_size_g: 160,
    calories_kcal: 260,
    protein_g: 6.0,
    fat_g: 10.5,
    carbs_g: 38.0,
  },
  {
    name: "Pani Puri / Golgappa",
    brand: null,
    category: "Snack",
    serving_size_g: 80,
    calories_kcal: 220,
    protein_g: 3.5,
    fat_g: 7.5,
    carbs_g: 37.0,
  },
  {
    name: "Bhel Puri",
    brand: null,
    category: "Snack",
    serving_size_g: 150,
    calories_kcal: 175,
    protein_g: 4.5,
    fat_g: 5.5,
    carbs_g: 30.0,
  },
  {
    name: "Kachori (Dal / Onion)",
    brand: null,
    category: "Snack",
    serving_size_g: 60,
    calories_kcal: 340,
    protein_g: 6.0,
    fat_g: 18.5,
    carbs_g: 40.0,
  },
  {
    name: "Dhokla (steamed chickpea snack)",
    brand: null,
    category: "Snack",
    serving_size_g: 100,
    calories_kcal: 160,
    protein_g: 5.5,
    fat_g: 4.5,
    carbs_g: 26.0,
  },
  {
    name: "Sev (crispy chickpea noodles)",
    brand: null,
    category: "Snack",
    serving_size_g: 30,
    calories_kcal: 500,
    protein_g: 14.0,
    fat_g: 28.0,
    carbs_g: 54.0,
  },
  {
    name: "Chakli (rice flour spirals)",
    brand: null,
    category: "Snack",
    serving_size_g: 30,
    calories_kcal: 470,
    protein_g: 7.0,
    fat_g: 22.0,
    carbs_g: 62.0,
  },
  {
    name: "Murukku",
    brand: null,
    category: "Snack",
    serving_size_g: 30,
    calories_kcal: 480,
    protein_g: 7.5,
    fat_g: 24.0,
    carbs_g: 60.0,
  },
  {
    name: "Chivda (Poha Chivda)",
    brand: null,
    category: "Snack",
    serving_size_g: 40,
    calories_kcal: 420,
    protein_g: 8.0,
    fat_g: 18.0,
    carbs_g: 60.0,
  },
  {
    name: "Papdi Chaat",
    brand: null,
    category: "Snack",
    serving_size_g: 150,
    calories_kcal: 195,
    protein_g: 5.5,
    fat_g: 7.5,
    carbs_g: 30.0,
  },
  {
    name: "Dahi Puri",
    brand: null,
    category: "Snack",
    serving_size_g: 150,
    calories_kcal: 185,
    protein_g: 5.0,
    fat_g: 6.0,
    carbs_g: 31.0,
  },

  // ── Sweets / Desserts ────────────────────────────────────────────────────────
  {
    name: "Gulab Jamun (fried milk solid in syrup)",
    brand: null,
    category: "Sweet",
    serving_size_g: 60,
    calories_kcal: 375,
    protein_g: 5.0,
    fat_g: 13.5,
    carbs_g: 61.0,
  },
  {
    name: "Rasgulla (spongy cheese balls in syrup)",
    brand: null,
    category: "Sweet",
    serving_size_g: 80,
    calories_kcal: 186,
    protein_g: 6.5,
    fat_g: 1.5,
    carbs_g: 40.0,
  },
  {
    name: "Kheer (Rice Pudding)",
    brand: null,
    category: "Sweet",
    serving_size_g: 150,
    calories_kcal: 158,
    protein_g: 4.5,
    fat_g: 5.5,
    carbs_g: 25.0,
  },
  {
    name: "Sooji Halwa (Semolina)",
    brand: null,
    category: "Sweet",
    serving_size_g: 100,
    calories_kcal: 295,
    protein_g: 4.5,
    fat_g: 12.5,
    carbs_g: 45.0,
  },
  {
    name: "Jalebi",
    brand: null,
    category: "Sweet",
    serving_size_g: 50,
    calories_kcal: 358,
    protein_g: 3.5,
    fat_g: 10.0,
    carbs_g: 65.0,
  },
  {
    name: "Besan Ladoo",
    brand: null,
    category: "Sweet",
    serving_size_g: 40,
    calories_kcal: 438,
    protein_g: 8.5,
    fat_g: 20.0,
    carbs_g: 58.0,
  },
  {
    name: "Barfi (Milk Fudge)",
    brand: null,
    category: "Sweet",
    serving_size_g: 40,
    calories_kcal: 380,
    protein_g: 7.5,
    fat_g: 14.0,
    carbs_g: 58.0,
  },
  {
    name: "Gajar Halwa (Carrot)",
    brand: null,
    category: "Sweet",
    serving_size_g: 100,
    calories_kcal: 245,
    protein_g: 4.0,
    fat_g: 10.5,
    carbs_g: 36.0,
  },
  {
    name: "Sandesh (Bengali sweet)",
    brand: null,
    category: "Sweet",
    serving_size_g: 40,
    calories_kcal: 280,
    protein_g: 7.5,
    fat_g: 9.5,
    carbs_g: 44.0,
  },
  {
    name: "Mysore Pak",
    brand: null,
    category: "Sweet",
    serving_size_g: 40,
    calories_kcal: 480,
    protein_g: 7.0,
    fat_g: 28.0,
    carbs_g: 56.0,
  },
  {
    name: "Rava Kesari",
    brand: null,
    category: "Sweet",
    serving_size_g: 100,
    calories_kcal: 280,
    protein_g: 4.0,
    fat_g: 10.0,
    carbs_g: 46.0,
  },
  {
    name: "Motichoor Ladoo",
    brand: null,
    category: "Sweet",
    serving_size_g: 45,
    calories_kcal: 395,
    protein_g: 5.5,
    fat_g: 14.5,
    carbs_g: 64.0,
  },

  // ── Drinks ───────────────────────────────────────────────────────────────────
  {
    name: "Masala Chai (with milk & sugar)",
    brand: null,
    category: "Drink",
    serving_size_g: 150,
    calories_kcal: 54,
    protein_g: 1.8,
    fat_g: 1.8,
    carbs_g: 8.0,
  },
  {
    name: "Sweet Lassi",
    brand: null,
    category: "Drink",
    serving_size_g: 250,
    calories_kcal: 98,
    protein_g: 3.5,
    fat_g: 3.5,
    carbs_g: 13.5,
  },
  {
    name: "Mango Lassi",
    brand: null,
    category: "Drink",
    serving_size_g: 300,
    calories_kcal: 95,
    protein_g: 3.0,
    fat_g: 2.5,
    carbs_g: 17.5,
  },
  {
    name: "Chaas / Buttermilk (spiced)",
    brand: null,
    category: "Drink",
    serving_size_g: 250,
    calories_kcal: 35,
    protein_g: 2.5,
    fat_g: 0.8,
    carbs_g: 5.0,
  },
  {
    name: "Nimbu Pani (Lemonade)",
    brand: null,
    category: "Drink",
    serving_size_g: 250,
    calories_kcal: 30,
    protein_g: 0.2,
    fat_g: 0.1,
    carbs_g: 8.5,
  },
  {
    name: "Thandai",
    brand: null,
    category: "Drink",
    serving_size_g: 250,
    calories_kcal: 110,
    protein_g: 4.0,
    fat_g: 5.0,
    carbs_g: 14.0,
  },
  {
    name: "Rose Sharbat",
    brand: null,
    category: "Drink",
    serving_size_g: 200,
    calories_kcal: 72,
    protein_g: 0.1,
    fat_g: 0.0,
    carbs_g: 18.5,
  },

  // ── Dairy / Staples ───────────────────────────────────────────────────────────
  {
    name: "Paneer (Indian Cottage Cheese)",
    brand: null,
    category: "Dairy",
    serving_size_g: 100,
    calories_kcal: 265,
    protein_g: 18.3,
    fat_g: 20.8,
    carbs_g: 1.2,
  },
  {
    name: "Dahi / Curd (full-fat)",
    brand: null,
    category: "Dairy",
    serving_size_g: 150,
    calories_kcal: 60,
    protein_g: 3.1,
    fat_g: 3.2,
    carbs_g: 4.8,
  },
  {
    name: "Ghee (Clarified Butter)",
    brand: null,
    category: "Dairy",
    serving_size_g: 10,
    calories_kcal: 900,
    protein_g: 0.0,
    fat_g: 99.5,
    carbs_g: 0.0,
  },
  {
    name: "Whole Wheat Atta (raw)",
    brand: null,
    category: "Dairy",
    serving_size_g: 30,
    calories_kcal: 341,
    protein_g: 11.8,
    fat_g: 1.7,
    carbs_g: 69.4,
  },
  {
    name: "Besan (Chickpea Flour, raw)",
    brand: null,
    category: "Dairy",
    serving_size_g: 30,
    calories_kcal: 360,
    protein_g: 22.5,
    fat_g: 5.6,
    carbs_g: 57.8,
  },
  {
    name: "Maida (Refined Wheat Flour, raw)",
    brand: null,
    category: "Dairy",
    serving_size_g: 30,
    calories_kcal: 348,
    protein_g: 10.4,
    fat_g: 0.9,
    carbs_g: 74.8,
  },
  {
    name: "Poha / Flattened Rice (raw)",
    brand: null,
    category: "Dairy",
    serving_size_g: 60,
    calories_kcal: 356,
    protein_g: 6.0,
    fat_g: 1.0,
    carbs_g: 78.5,
  },
  {
    name: "Amul Taaza Full Cream Milk",
    brand: "Amul",
    category: "Dairy",
    serving_size_g: 200,
    calories_kcal: 65,
    protein_g: 3.4,
    fat_g: 3.5,
    carbs_g: 4.8,
  },

  // ── Cooked Vegetables ────────────────────────────────────────────────────────
  {
    name: "Bhindi / Okra (sabzi, cooked)",
    brand: null,
    category: "Vegetable",
    serving_size_g: 150,
    calories_kcal: 75,
    protein_g: 2.5,
    fat_g: 4.0,
    carbs_g: 9.0,
  },
  {
    name: "Aloo Sabzi (Potato, cooked spiced)",
    brand: null,
    category: "Vegetable",
    serving_size_g: 150,
    calories_kcal: 110,
    protein_g: 2.0,
    fat_g: 4.5,
    carbs_g: 17.0,
  },
  {
    name: "Baingan / Eggplant Sabzi",
    brand: null,
    category: "Vegetable",
    serving_size_g: 150,
    calories_kcal: 65,
    protein_g: 1.5,
    fat_g: 3.5,
    carbs_g: 9.0,
  },
  {
    name: "Palak Sabzi (Spinach, cooked)",
    brand: null,
    category: "Vegetable",
    serving_size_g: 150,
    calories_kcal: 65,
    protein_g: 2.8,
    fat_g: 3.5,
    carbs_g: 7.5,
  },
  {
    name: "Gobhi / Cauliflower Sabzi",
    brand: null,
    category: "Vegetable",
    serving_size_g: 150,
    calories_kcal: 72,
    protein_g: 2.5,
    fat_g: 4.0,
    carbs_g: 9.0,
  },
  {
    name: "Methi / Fenugreek Leaves Sabzi",
    brand: null,
    category: "Vegetable",
    serving_size_g: 150,
    calories_kcal: 55,
    protein_g: 3.0,
    fat_g: 2.5,
    carbs_g: 8.0,
  },
  {
    name: "Lauki / Bottle Gourd Sabzi",
    brand: null,
    category: "Vegetable",
    serving_size_g: 150,
    calories_kcal: 45,
    protein_g: 1.2,
    fat_g: 2.5,
    carbs_g: 6.5,
  },
  {
    name: "Karela / Bitter Gourd Sabzi",
    brand: null,
    category: "Vegetable",
    serving_size_g: 150,
    calories_kcal: 60,
    protein_g: 2.0,
    fat_g: 3.0,
    carbs_g: 8.0,
  },
  {
    name: "Tinda / Round Gourd Sabzi",
    brand: null,
    category: "Vegetable",
    serving_size_g: 150,
    calories_kcal: 50,
    protein_g: 1.5,
    fat_g: 2.5,
    carbs_g: 7.5,
  },

  // ── Popular Indian Brands ────────────────────────────────────────────────────
  {
    name: "Parle-G Glucose Biscuits",
    brand: "Parle",
    category: "Brand",
    serving_size_g: 71,
    calories_kcal: 450,
    protein_g: 7.0,
    fat_g: 12.0,
    carbs_g: 77.0,
  },
  {
    name: "Britannia Marie Gold Biscuits",
    brand: "Britannia",
    category: "Brand",
    serving_size_g: 75,
    calories_kcal: 443,
    protein_g: 8.3,
    fat_g: 11.0,
    carbs_g: 77.0,
  },
  {
    name: "Haldiram's Bhujia Sev",
    brand: "Haldiram's",
    category: "Brand",
    serving_size_g: 30,
    calories_kcal: 530,
    protein_g: 15.0,
    fat_g: 32.0,
    carbs_g: 50.0,
  },
  {
    name: "Haldiram's Aloo Bhujia",
    brand: "Haldiram's",
    category: "Brand",
    serving_size_g: 30,
    calories_kcal: 510,
    protein_g: 9.0,
    fat_g: 29.0,
    carbs_g: 58.0,
  },
  {
    name: "Amul Butter (salted)",
    brand: "Amul",
    category: "Brand",
    serving_size_g: 10,
    calories_kcal: 720,
    protein_g: 0.5,
    fat_g: 80.0,
    carbs_g: 0.5,
  },
  {
    name: "Amul Processed Cheese",
    brand: "Amul",
    category: "Brand",
    serving_size_g: 20,
    calories_kcal: 296,
    protein_g: 16.5,
    fat_g: 23.0,
    carbs_g: 4.5,
  },
  {
    name: "Maggi 2-Minute Noodles (masala)",
    brand: "Maggi",
    category: "Brand",
    serving_size_g: 70,
    calories_kcal: 384,
    protein_g: 7.5,
    fat_g: 15.0,
    carbs_g: 56.0,
  },
  {
    name: "Britannia Good Day Cashew Cookies",
    brand: "Britannia",
    category: "Brand",
    serving_size_g: 75,
    calories_kcal: 497,
    protein_g: 7.0,
    fat_g: 22.0,
    carbs_g: 68.0,
  },
  {
    name: "Sunfeast Dark Fantasy Biscuits",
    brand: "Sunfeast",
    category: "Brand",
    serving_size_g: 75,
    calories_kcal: 503,
    protein_g: 6.0,
    fat_g: 24.0,
    carbs_g: 67.0,
  },
  {
    name: "MDH Garam Masala",
    brand: "MDH",
    category: "Brand",
    serving_size_g: 5,
    calories_kcal: 315,
    protein_g: 12.0,
    fat_g: 8.0,
    carbs_g: 52.0,
  },
  {
    name: "MTR Masala Dosa Ready Mix",
    brand: "MTR",
    category: "Brand",
    serving_size_g: 100,
    calories_kcal: 350,
    protein_g: 12.0,
    fat_g: 2.5,
    carbs_g: 70.0,
  },
  {
    name: "MTR Dal Makhani (Ready to Eat)",
    brand: "MTR",
    category: "Brand",
    serving_size_g: 300,
    calories_kcal: 105,
    protein_g: 5.0,
    fat_g: 4.5,
    carbs_g: 13.0,
  },
  {
    name: "Haldiram's Moong Dal Namkeen",
    brand: "Haldiram's",
    category: "Brand",
    serving_size_g: 30,
    calories_kcal: 490,
    protein_g: 18.0,
    fat_g: 24.0,
    carbs_g: 54.0,
  },
  {
    name: "Parle Monaco Salted Crackers",
    brand: "Parle",
    category: "Brand",
    serving_size_g: 30,
    calories_kcal: 460,
    protein_g: 8.0,
    fat_g: 16.0,
    carbs_g: 73.0,
  },
  {
    name: "ITC Sunfeast Yippee Noodles",
    brand: "Sunfeast",
    category: "Brand",
    serving_size_g: 70,
    calories_kcal: 370,
    protein_g: 7.5,
    fat_g: 13.5,
    carbs_g: 57.0,
  },
];

import { getDb } from "./migrate";

export async function seedIndianFoods(): Promise<void> {
  const db = await getDb();

  // Check if already seeded
  const existing = await db.getFirstAsync<{ count: number }>(
    "SELECT COUNT(*) as count FROM foods WHERE user_id = 'system'"
  );
  if (existing && existing.count >= 50) {
    console.log("[Seed] Indian foods already seeded, skipping.");
    return;
  }

  console.log("[Seed] Seeding Indian foods database...");

  for (const food of INDIAN_FOODS_SEED) {
    const id = `indian_${food.name.toLowerCase().replace(/[^a-z0-9]/g, "_").slice(0, 50)}`;
    await db.runAsync(
      `INSERT OR IGNORE INTO foods
       (id, name, brand, barcode, serving_size_g, calories_kcal, protein_g, fat_g, carbs_g, source, user_id, created_at, updated_at)
       VALUES (?, ?, ?, NULL, ?, ?, ?, ?, ?, 'indian_seed', 'system', datetime('now'), datetime('now'))`,
      [
        id,
        food.name,
        food.brand ?? null,
        food.serving_size_g,
        food.calories_kcal,
        food.protein_g,
        food.fat_g,
        food.carbs_g,
      ]
    );
  }

  console.log(`[Seed] ✅ Seeded ${INDIAN_FOODS_SEED.length} Indian foods`);
}
